// Generated from the client's photo set (78 images, 2026-08-08).
// Originals were shot on a phone and are kept out of the deploy in source-photos/.
// Each image here has been EXIF-rotated, brightened, sharpened and resized:
//   /assets/villa/<id>.jpg        up to 1600px  — used by the lightbox
//   /assets/villa/thumbs/<id>.jpg up to  640px  — used by the gallery grid
// w/h are the real dimensions, so layouts can respect portrait vs landscape.
// Counts — exterior: 14, pool: 17, balcony: 6, interior: 23, bedroom: 15, grounds: 1, excursion: 2.

export const GALLERY_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'exterior', label: 'The Villa' },
  { id: 'pool', label: 'Pool & Deck' },
  { id: 'interior', label: 'Interiors' },
  { id: 'bedroom', label: 'Bedrooms' },
  { id: 'balcony', label: 'Views' },
  { id: 'excursion', label: 'Excursions' },
]

export const GALLERY = [
  { id: 'exterior-09', cat: 'exterior', w: 1600, h: 1200, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-08', cat: 'pool', w: 1600, h: 1228, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'balcony-06', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'exterior-13', cat: 'exterior', w: 1600, h: 1200, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'interior-02', cat: 'interior', w: 1600, h: 1200, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-04', cat: 'bedroom', w: 1149, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'pool-06', cat: 'pool', w: 1600, h: 1221, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'exterior-10', cat: 'exterior', w: 1600, h: 1200, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'balcony-03', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'interior-03', cat: 'interior', w: 1600, h: 1200, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'pool-09', cat: 'pool', w: 1600, h: 1195, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'exterior-12', cat: 'exterior', w: 1280, h: 960, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'exterior-01', cat: 'exterior', w: 1600, h: 1184, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-01', cat: 'pool', w: 1200, h: 1600, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'balcony-01', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'interior-01', cat: 'interior', w: 1600, h: 1200, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-01', cat: 'bedroom', w: 1600, h: 1176, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'grounds-01', cat: 'grounds', w: 1600, h: 1200, caption: 'The Grounds', alt: 'The villa grounds' },
  { id: 'excursion-01', cat: 'excursion', w: 1600, h: 1247, caption: 'Island Excursions', alt: 'An island excursion near Discovery Bay' },
  { id: 'exterior-02', cat: 'exterior', w: 1600, h: 1216, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-02', cat: 'pool', w: 1200, h: 1600, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'balcony-02', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'interior-04', cat: 'interior', w: 960, h: 1280, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-02', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'excursion-02', cat: 'excursion', w: 1080, h: 1123, caption: 'Island Excursions', alt: 'An island excursion near Discovery Bay' },
  { id: 'exterior-03', cat: 'exterior', w: 1180, h: 1600, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-03', cat: 'pool', w: 1600, h: 1185, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'balcony-04', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'interior-05', cat: 'interior', w: 960, h: 1280, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-03', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-04', cat: 'exterior', w: 1280, h: 960, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-04', cat: 'pool', w: 1600, h: 1195, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'balcony-05', cat: 'balcony', w: 1280, h: 960, caption: 'Balcony & Sea Views', alt: 'Caribbean Sea view from a villa balcony' },
  { id: 'interior-06', cat: 'interior', w: 720, h: 1280, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-05', cat: 'bedroom', w: 720, h: 1280, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-05', cat: 'exterior', w: 960, h: 1280, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-05', cat: 'pool', w: 1200, h: 1600, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-07', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-06', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-06', cat: 'exterior', w: 720, h: 1280, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-07', cat: 'pool', w: 1600, h: 1213, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-08', cat: 'interior', w: 1201, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-07', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-07', cat: 'exterior', w: 720, h: 1280, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-10', cat: 'pool', w: 1280, h: 960, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-09', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-08', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-08', cat: 'exterior', w: 1600, h: 1200, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-11', cat: 'pool', w: 960, h: 1280, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-10', cat: 'interior', w: 1172, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-09', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-11', cat: 'exterior', w: 1600, h: 1200, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-12', cat: 'pool', w: 960, h: 1280, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-11', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-10', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'exterior-14', cat: 'exterior', w: 1200, h: 1600, caption: 'Sea View Mirage Villa', alt: 'Sea View Mirage Villa exterior' },
  { id: 'pool-13', cat: 'pool', w: 960, h: 1280, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-12', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-11', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'pool-14', cat: 'pool', w: 960, h: 1280, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-13', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-12', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'pool-15', cat: 'pool', w: 1280, h: 960, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-14', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-13', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'pool-16', cat: 'pool', w: 1600, h: 1200, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-15', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-14', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'pool-17', cat: 'pool', w: 1200, h: 1600, caption: 'The Pool Deck', alt: 'The pool deck at Sea View Mirage Villa' },
  { id: 'interior-16', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'bedroom-15', cat: 'bedroom', w: 1200, h: 1600, caption: 'Bedroom Suite', alt: 'A bedroom suite at Sea View Mirage Villa' },
  { id: 'interior-17', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-18', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-19', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-20', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-21', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-22', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
  { id: 'interior-23', cat: 'interior', w: 1200, h: 1600, caption: 'Inside the Villa', alt: 'Interior living space at Sea View Mirage Villa' },
]

export const photoSrc = id => `/assets/villa/${id}.jpg`
export const photoThumb = id => `/assets/villa/thumbs/${id}.jpg`
