import crypto from 'node:crypto'
import { json } from './_lib.mjs'

/**
 * Admin authentication for the villa's dashboard.
 *
 * One password, one person. No user table, no reset flow — anything more would
 * be machinery to maintain for a single login.
 *
 * The password is never stored, only a scrypt hash of it. Sessions are a signed
 * cookie rather than server state, because serverless instances share nothing.
 */

const COOKIE = 'villa_admin'
const SESSION_DAYS = 7
const SCRYPT_KEYLEN = 64

// scrypt cost. 2^15 keeps a single verification a few hundred milliseconds on
// Vercel's smaller instances — slow enough to make guessing expensive, fast
// enough that logging in does not feel broken.
const SCRYPT_PARAMS = { N: 32768, r: 8, p: 1, maxmem: 96 * 1024 * 1024 }

const scrypt = (password, salt) =>
  new Promise((resolve, reject) => {
    crypto.scrypt(password, salt, SCRYPT_KEYLEN, SCRYPT_PARAMS, (err, key) =>
      err ? reject(err) : resolve(key))
  })

/** `scrypt$<salt-hex>$<hash-hex>`. Generated by scripts/make-admin-password.mjs. */
export async function hashPassword(password) {
  const salt = crypto.randomBytes(16)
  const key = await scrypt(password, salt)
  return `scrypt$${salt.toString('hex')}$${key.toString('hex')}`
}

export async function verifyPassword(password, stored) {
  if (typeof stored !== 'string') return false
  const [scheme, saltHex, hashHex] = stored.split('$')
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false

  let expected, actual
  try {
    expected = Buffer.from(hashHex, 'hex')
    actual = await scrypt(password, Buffer.from(saltHex, 'hex'))
  } catch {
    return false
  }
  return expected.length === actual.length && crypto.timingSafeEqual(expected, actual)
}

// --- sessions ---------------------------------------------------------------

const sessionSecret = () => {
  const s = process.env.ADMIN_SESSION_SECRET
  if (!s || s.length < 32) {
    throw new Error('ADMIN_SESSION_SECRET is missing or too short (needs 32+ characters).')
  }
  return s
}

const sign = payload =>
  crypto.createHmac('sha256', sessionSecret()).update(payload).digest('hex')

/** `<expiry-ms>.<hmac>` — no identity in it, because there is only one admin. */
export function makeSession(days = SESSION_DAYS) {
  const exp = String(Date.now() + days * 86400_000)
  return `${exp}.${sign(exp)}`
}

export function readSession(token) {
  if (typeof token !== 'string' || !token.includes('.')) return null
  const idx = token.lastIndexOf('.')
  const exp = token.slice(0, idx)
  const mac = token.slice(idx + 1)
  if (!/^\d+$/.test(exp)) return null

  let expected
  try { expected = sign(exp) } catch { return null }
  const a = Buffer.from(expected, 'utf8')
  const b = Buffer.from(mac, 'utf8')
  // Signature first, then expiry — an expired token with a forged signature
  // should fail as a forgery, not merely as expired.
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null
  if (Number(exp) < Date.now()) return null
  return { exp: Number(exp) }
}

const parseCookies = header => {
  const out = {}
  for (const part of String(header || '').split(';')) {
    const i = part.indexOf('=')
    if (i < 1) continue
    out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim())
  }
  return out
}

export function setSessionCookie(res, token, days = SESSION_DAYS) {
  // HttpOnly so no script can read it; SameSite=Lax so it does not ride along
  // on cross-site requests; Secure because this only ever runs over HTTPS.
  res.setHeader('Set-Cookie',
    `${COOKIE}=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${days * 86400}`)
}

export function clearSessionCookie(res) {
  res.setHeader('Set-Cookie', `${COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`)
}

export const sessionFromRequest = req => readSession(parseCookies(req.headers?.cookie)[COOKIE])

/**
 * Gate for every /api/admin/* route. Returns true when the caller may proceed;
 * otherwise it has already sent a 401 and the handler must return.
 *
 *   if (!requireAdmin(req, res)) return
 */
export function requireAdmin(req, res) {
  if (sessionFromRequest(req)) return true
  json(res, 401, { error: 'Not signed in.' })
  return false
}

/**
 * Constant-ish delay on every login attempt.
 *
 * Serverless instances share no memory, so there is no honest way to count
 * failures across them — this is a speed bump, not rate limiting. The real
 * protection is a long random password and scrypt's own cost. Say so in
 * SETUP.md rather than implying more than this does.
 */
export const loginDelay = () => new Promise(r => setTimeout(r, 400))

export const ADMIN_COOKIE = COOKIE
